// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7y8ivITKHgcKrAOlisJII6mikn9bnr0',
    appId: '1:957444648715:web:964173b8d11e7be587bc0e',
    messagingSenderId: '957444648715',
    projectId: 'staff-sync-107fc',
    authDomain: 'staff-sync-107fc.firebaseapp.com',
    storageBucket: 'staff-sync-107fc.firebasestorage.app',
    measurementId: 'G-3810KM8ETN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBlrRePyZQY-8nDbzdfeP9vqK_1aMRqlg',
    appId: '1:957444648715:android:461f66349cf119f787bc0e',
    messagingSenderId: '957444648715',
    projectId: 'staff-sync-107fc',
    storageBucket: 'staff-sync-107fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEPQurJKdmiwQ0Mz8CEHEMYV7w_qvcCk4',
    appId: '1:957444648715:ios:1bf538b8c9990af987bc0e',
    messagingSenderId: '957444648715',
    projectId: 'staff-sync-107fc',
    storageBucket: 'staff-sync-107fc.firebasestorage.app',
    iosBundleId: 'com.example.staffSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEPQurJKdmiwQ0Mz8CEHEMYV7w_qvcCk4',
    appId: '1:957444648715:ios:1bf538b8c9990af987bc0e',
    messagingSenderId: '957444648715',
    projectId: 'staff-sync-107fc',
    storageBucket: 'staff-sync-107fc.firebasestorage.app',
    iosBundleId: 'com.example.staffSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7y8ivITKHgcKrAOlisJII6mikn9bnr0',
    appId: '1:957444648715:web:34de5797bd88304a87bc0e',
    messagingSenderId: '957444648715',
    projectId: 'staff-sync-107fc',
    authDomain: 'staff-sync-107fc.firebaseapp.com',
    storageBucket: 'staff-sync-107fc.firebasestorage.app',
    measurementId: 'G-JQ1SSRLVNZ',
  );
}
